### ISSUE TITLE
Tea Time doesn't wake up on Android 2.1 / Milestone

### ISSUE THREAD

**Issue by prodigy7** [ralphleon/TeaTimer#1]
I use a long time Tea Time on my Android 2.0.1 without any problems. Now I've upgraded (complete fresh install) my Milestone with Android 2.1 and since then, Tea Time doesn't bell if time is gone.

**Comment by ralphleon** [comment]
Could you try to go under:

Settings -> Notification Ditty

then change the notification sound? Could you tell me what it was set to?

**Comment by prodigy7** [comment]
I change the sound to "Bird loop" without success. Notification doesn't happend or too late. Interessting fact: If the time is gone and I wake up the phone with the power button, the notification comes up. So I think, somehow the process can't wakeup if screen is looked or/and device is in standby.

**Comment by prodigy7** [comment]
Sorry ... should reopend ... hit wrong button

**Comment by ralphleon** [comment]
No problem. Ok, one last thought: try to uninstall then reinstall the application. 

If this doesn't work, I'll be getting a droid in the mail in the next week or so! 

Thanks again for all the help!

**Comment by prodigy7** [comment]
Ok ... reinstalled the app but without success.
Maybe for better reproducing:
1. I set the tea time
2. Activate the tea timer
3. Set standby on my device (with power button)

Could maybe the lockscreen the reason? Which Android versions you've for testing?

**Comment by ralphleon** [comment]
I use a nexus one, which is also an android 2.1 device... This workflow is the exact same way I use the timer (successfully). This is really troublesome... Thankfully I'm going to google I/o and they're sending me a new droid in the mail. I'll test it first thing!

Does the notification even appear in the status bar?

**Comment by prodigy7** [comment]
Notification appear in status bar if happens
